
subroutine read_iseed(sys,IN_ISEED)
    !Description:
    !!@ details
    !> Subroutine read_iseed reads in the seed for the random number generator
    !> and then uses it to initialise the random number generator.  The seed
    !> is generated using /dev/urandom and the value is saved to disk.
    !
    ! initialise mersenee-twistor random number generator
    !
    ! Try using /dev/urandom to get a random number.
    ! /dev/urandom stores random numbers generated by analog sources of randomness
    ! such as hard disk timings, keystroke inputs, mouse movements, etc. It saves
    ! these things and makes a pool of random numbers.
    ! This can fail if /dev/urandom's pool of random numbers is depleted.
    ! If it does you'll probably get the same number over and over again.
    ! If you're worried your numbers aren't random enough,
    ! use /dev/random instead. This will just refuse to spit out a random number
    ! if it's pool of random numbers has run out.
    !
    !\param[in] sys The molsysdat object
    !\param[in] IN_ISEED The relative path to the file where the seed value is saved

    use molecule_specs
    use mt19937

    type (molsysdat) :: sys
    character(len=80) :: IN_ISEED
 
    call system('od -vAn -N4 -td4 < /dev/urandom > '//trim(IN_ISEED))
    open(unit=7,file=trim(IN_ISEED),status='old')
    read(7,*) i
    close(7)
    sys%iseed = abs(i)

    call init_genrand(sys%iseed)
    print *, 'first rand ',genrand_real3(), 'iseed ',sys%iseed

    return
end
